### ISSUE TITLE
Determining whether a Voronoi cell is at the edge of the box

### ISSUE THREAD

**Issue by shoubhikraj** [chr1shr/voro#20]
I am using voro++ in a program for analysis of molecular dynamics trajectories (i.e. 3D coordinates). The main part involves calculating Voronoi cells for each atom, and then determining the density of that cell.

However, the problem is that in my case, there is no periodic boundary condition, so the particles that are at the edge should have infinitely large voronoi cells, if I understand correctly. This is fine, because I can then set the density to zero. But, I am not sure what would be the best way to do this.

One of the things I could do is to make a box large enough to contain all the particles (atoms) and then loop through each cell, finding if more than two of their vertices lie on any one of the faces of the box (which would mean that the cell would be infinite if the box was removed). But this seems too complicated, and unnecessary.

Is there any function in voro++ which can do this in a simpler way? The only thing to find out is whether the cell would be infinite when the box is removed. Any help is greatly appreciated.

**Comment by chr1shr** [comment]
Your code looks correct. I assume that all of your particles have IDs that are &ge; 0. In that case the only negative numbers in the neighbor list will be from the boundary.

Internally, Voro++ sorts the particles into a grid of blocks, which greatly aids in speeding up the computation. When you are building the Voronoi cell for particular particle, you need to rapidly find nearby particles, and this can be done efficiently by looking at the particles in the nearby blocks.

There is a tradeoff in the block size. If the blocks are too large (_e.g._ 100 particles per block) then it's still not very efficient because you still need to consider a large number of particles that are probably not so relevant. But if the blocks are too small (_e.g._ 1 particle per block) then it also becomes inefficient because you have scan through a very large number of blocks. In my tests of randomly distributed particles in a region, I typically find that ~5 particles per block is a good number.

I think good analogy is storing cooking equipment in kitchen cupboards. You wouldn't want to design a kitchen with just one giant cupboard, because you'd spend all your time rummaging around in it to find what you need. But equally you wouldn't design individual cupboards for every different utensil because you'd spend all your time opening cupboard doors to get what you need. Thus a happy medium (which is how most kitchens are designed) would be most effective.

If you pad the domain, I am not quite sure what the optimal block number will work out as. You could run some timing tests to look at this. There may be a small performance hit, but I expect that it won't affect the performance too much. I think this is a good starting point for choosing: suppose you had a domain of size L &times; L &times; L and you were using N &times; N &times; N blocks for optimal calculations. Then if you created a padded domain of size 3L &times; 3L &times; 3L, you could try 3N &times; 3N &times; 3N blocks. That would mean that in the part of the domain with the particles, the number of particles per block would be roughly close to the optimal. 

(By the way we currently have a version in development that does multithreading, and we aim to release this in a few months. Voro++ is very well structured for multithreading.)

**Comment by chr1shr** [comment]
Yes, setting the initial block memory to 1 makes sense so that the amount of memory allocated in the empty regions is small.
