### ISSUE TITLE
make install fails to install required headers

### ISSUE THREAD

**Issue by nathan-miller-LANL** [chr1shr/voro#24]
The cmake installation process is currently failing on master. When I configure the code to install into a user specified directory by setting `CMAKE_INSTALL_PREFIX` the build and installation commands evaluate but only `voro++.hh` is installed. When the library is compiled into additional code subsequently the following error arises:

    /my/cmake/install/prefix/include/voro++.hh:320:10: fatal error: config.hh: No such file or directory
     #include "config.hh"

which I take to mean the additional header files are required. If I change the line (line CMakeLists.txt:66 in [56d619f](https://github.com/chr1shr/voro/commit/56d619faf3479313399516ad71c32773c29be859))

    file(GLOB_RECURSE VORO_HEADERS src/voro++.hh)

to

    file(GLOB_RECURSE VORO_HEADERS src/*.hh)

it fixes the issue.

I also attempted to build and install the dev branch but compilation is currently broken so I was unable to.

**Comment by chr1shr** [comment]
Yes, the additional header files are required, and the installation should also copy them into the target include directory.

I don't use CMake myself, and I have relied on volunteers to keep this up to date. If you submit a pull request for this I will merge it.

We have been working on the dev branch a lot during the past few months, and it is close to release. It has a number of new features, such as OpenMP support, dedicated 2D computations, and command-line utility improvements. You should be able to compile it via the Makefile, but the CMakelists.txt file will definitely need updating since many of the source code files have been moved around.
