### ISSUE TITLE
Question when I generated mesh with dense packing.

### ISSUE THREAD

**Issue by zjufrcon** [chr1shr/voro#33]
Hi,

I am using voro++ command line :  voro++ -yp -yv -wb -12 12 -6 6 -10 10 -12 12 -6 6 -10 10 pack_1_cylin to generated voro cells and I want to calculated the local void of this packing(more than 10k particles and monodisperse, the radius is 150mm).
But in the file "pack_1_cylin.vol", the last column which refers to the volume cell(around 0.02) is much smaller than my radius of particles, are there any settings or parameters I missed in the command line?

Thanks for replying!

**Comment by chr1shr** [comment]
First, let me note that you do not need to add the `-wb -12 12 -6 6 -10 10` options. For non-periodic computations Voro++ already puts walls at the domain boundary. The `-wb` option is only required in the more specialized case where you want to do a Voronoi tessellation in a box, but you want to consider the influence of particles outside that box. In that case, you can make the container larger, in order to encompass those exterior particles.

Overall, your command-line usage looks correct and it is difficult for me to assess what the problem is. You mention a particle radius of 150&nbsp;mm, but I don't see how that connects to the scale of the container geometry. Are those values of -12, 12, *etc.* given in meters, millimeters, or something else?

Based on your domain size of 24 &times; 12 &times; 20, which has volume 5760, then if you have 10000 particles the average Voronoi volume should be 0.5760. But if the particles are distributed unevenly, it possible you might have many smaller Voronoi cells with volume 0.02, and some larger ones.

**Comment by zjufrcon** [comment]
Thanks for reply, my box has length of 24 meters *12meters*20meters, and particle radius is 0.15m, and number of particles is 200K, and the voronoi cells with volume around 0.02 to 0.04. Here I am confused when I compute the local fraction with volume_particle/volume_cell, and the value of radius for the calculation of volume_particle is unclear to me, if I chose the 0.15m, then the volume_particle=0.07 is larger than the voronoi cell, or there is something wrong with my system, maybe overlap is large between particles, because I used cohesive model to build system.

**Comment by chr1shr** [comment]
If your particles are hard non-overlapping spheres of radius *R*, then all of the corresponding Voronoi cells should completely encompass each particle, and therefore have volumes greater than 4 &pi; *R*&sup3;/3. If you aren't seeing that, it suggests that you have overlapping particles, where the particle centers are closer than 2*R* apart. That is definitely possible with a cohesive model. You could look at using [radial distribution function](https://en.wikipedia.org/wiki/Radial_distribution_function), which is a way to characterize the inter-particle separation distances. That will show you if you have many particles that are closer than 2*R* from each other.
