### ISSUE TITLE
neigbors method return negative numbers 

### ISSUE THREAD

**Issue by vlccek** [chr1shr/voro#39]
Thank you for providing this incredible library.

I'm currently using the development branch of voro to take advantage of its parallel processing features. However, I've come across a challenge with the neighbour identification feature, which occasionally returns negative values. Are these negative numbers indicative of a specific issue, or an overflow?

**Comment by chr1shr** [comment]
Negative values in the neighbor list correspond to Voronoi faces that:

- touch the domain boundary, in a non-periodic domain,
- are due to images of the current particle, in a periodic domain.

This issue is discussed in some of the documentation, *e.g.* the description of neighbor lists under the %n option on the [custom output reference](https://math.lbl.gov/voro++/doc/custom.html).
